### ISSUE TITLE
Issue with parsing errors on associated models

### ISSUE THREAD

**Issue by glappen** [balvig/spyke#110]
Hello,

I just encountered an issue where my API returns errors for an associated object. Let's say I have a User model, and a User has-many UserRoles. The errors json returned from my API looks like this:
```
{:errors=>
  {
    :email=>[
      {:error=>"blank"}
    ], 
    :"user_roles.years_of_experience"=>[{:error=>"blank"}]
  }
}
```

That is what I get when I call render json: { errors: @user.errors.details } in my API.

The error I get from Spyke is:

```
undefined method `user_roles.years_of_experience' for #<CoreClient::User:0x00007f1868008a70>
spyke (5.3.4) lib/spyke/attribute_assignment.rb:101:in `method_missing'
activemodel (5.2.2.1) lib/active_model/errors.rb:420:in `generate_message'
activemodel (5.2.2.1) lib/active_model/errors.rb:454:in `normalize_message'
activemodel (5.2.2.1) lib/active_model/errors.rb:298:in `add'
spyke (5.3.4) lib/spyke/http.rb:108:in `block (2 levels) in add_errors_to_model'
```

Is there any support for Spyke parsing errors for associated objects, or is it only working for attributes one level deep in the model being created? Maybe I'm not putting errors hash into the correct format.

Thanks!

Greg

**Comment by balvig** [comment]
@glappen looks like maybe you have indeed stumbled on a bug!
I believe the hash is in the correct format, but Spyke is not able to handle nested errors properly yet 🤔

**Comment by glappen** [comment]
I need to get it working so maybe I can implement it for Spyke. Can you
perhaps point me to where the logic should go?

Thanks!

**Comment by glappen** [comment]
@balvig I have spent some time reviewing the spyke code, but I am still not sure how best to add this support. Do you have some suggestions on where to start? Thanks!

**Comment by balvig** [comment]
@glappen I've added a failing spec here: https://github.com/balvig/spyke/compare/master...jb%2Fnested-errors

The problem seems to be that while Spyke uses `ActiveModel` to add errors onto the model:

https://github.com/balvig/spyke/blob/f7d7076e89a9bb0bd81516651a2409151222eed5/lib/spyke/http.rb#L108

...it however doesn't seem to support the `xxx.yyy` shortcut for adding errors to associations.
