### ISSUE TITLE
How to custom params and routes on a has_many relationship

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#8]
Hello, 

I have a scenario that does not fit on this kind of example on readme. I have no idea how I can change some behaviors on your gem. I have a folder inside models, that makes me use a namespace. I figured out that I can specify uri with the method uri, but how I can access a relationship. I am not able top fetch the nested relationship data. Below follows the code and output on terminal.

```ruby
class Tro::Occurrence < Spyke::Base
  uri '/occurrences'

  has_many :photos, uri: '/occurrences/:occurrences_id/photos'
  has_many :voice_records
end


output 

Tro::Occurrence.find(1).photos
  Spyke (107.6ms)  GET http://localhost:3000/occurrences?id=1 [200]
=> #<Spyke::Associations::HasMany:0x000000016541d0
 @klass=
  Photo(id: integer, element_id: integer, description: string, taken_at: datetime, photographer: string, image_file_name: string, image_content_type: string, image_file_size: integer, image_updated_at: datetime, created_at: datetime, updated_at: datetime, order: integer, processing_url: string, image_processing: boolean),
 @name=:photos,
 @options={:uri=>"/occurrences/:occurrences_id/photos", :type=>Spyke::Associations::HasMany},
 @params={:tro_occurrence_id=>nil},
 @parent=
  #<Tro::Occurrence(/occurrences) id: nil {"id"=>1, "title"=>"Título legal", "description"=>"Descrição mais legal ainda.", "x"=>-19.1513555390899, "y"=>-48.9631083745888, "token"=>"6ut5jcd5kbs4ffffffffaba9c71a", "updated_at"=>"2015-01-16T16:29:50.788Z", "created_at"=>"2015-01-16T16:29:50.788Z", "urgency"=>3, "photos"=>[], "voice_record"=>nil}: nil {"id"=>2, "title"=>"Acidente com Ferrari", "description"=>"Happens", "x"=>-19.1513566666667, "y"=>-48.9631044444444, "token"=>"6ut5jcd5kbr5ffffffffaba9c71a", "updated_at"=>"2015-01-16T16:29:54.347Z", "created_at"=>"2015-01-16T16:29:54.347Z", "urgency"=>5, "photos"=>[{"description"=>"Oh noes!", "image"=>"http://s3.amazonaws.com/teste/photos/images/1/original.jpg?1421425790", "medium"=>"http://s3.amazonaws.com/testephotos/images/1/medium.jpg?1421425790", "thumb"=>"http://s3.amazonaws.com/teste/photos/images/1/thumb.jpg?1421425790"}], "voice_record"=>nil}: nil>>



error: 

Tro::Occurrence.all.first.photos.first
  Spyke (12.0ms)  GET http://localhost:3000/occurrences [200]
NoMethodError: undefined method `new_collection_from_result' for #<Class:0x0000000da97ad8>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@teste/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'

```

**Comment by balvig** [comment]
Does changing it to this help? (ie singular foreign_key)

```ruby
has_many :photos, uri: '/occurrences/:occurrence_id/photos'
```

**Comment by thiagocifani** [comment]
Yep. It gave me 

```
Tro::Occurrence.find(1).photos.first
  Spyke (17.7ms)  GET http://localhost:3000/occurrences?id=1 [200]
NoMethodError: super: no superclass method `fetch' for #<Spyke::Associations::HasMany:0x000000011d5c58>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@sigvia/gems/spyke-1.5.0/lib/spyke/relation.rb:50:in `method_missing'

´´´

**Comment by balvig** [comment]
Ah, also can you change your `Occurence` class to this:

```
 uri '/occurrences/:id'
```

Spyke is adding the id as a param because it doesn't see it as part of the UIR :)

**Comment by balvig** [comment]
Also, you'll need a Photo class (not clear if you have that already!)

**Comment by thiagocifani** [comment]
Same behavior.

```ruby
Tro::Occurrence.find(1).photos.first
  Spyke (8.9ms)  GET http://localhost:3000/occurrences/1 [200]
NoMethodError: undefined method `new_collection_from_result' for #<Class:0x0000000112f2e0>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@sigvia/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'


class Tro::Photo < Spyke::Base
  uri '/photos/:id'
end

```

**Comment by balvig** [comment]
(oh, also if you can, please update to Spyke 1.6! :grin: )

**Comment by thiagocifani** [comment]
This namespace on params is correct, or it could be a problem too?

@name=:photos,
 @options={:uri=>"/occurrences/:occurrence_id/photos", :type=>Spyke::Associations::HasMany},
 @params={:tro_occurrence_id=>1},  --  this one

**Comment by thiagocifani** [comment]
I dont have routes for photos besides the nested one.

**Comment by balvig** [comment]
ah yeh that looks a bit fishy... just for the sake of debugging, could you try changing it to

```ruby
has_many :photos, uri: '/occurrences/:tro_occurrence_id/photos'
```

**Comment by thiagocifani** [comment]
same output

´´´ruby
NoMethodError: undefined method `new_collection_from_result' for #<Class:0x0000000c6b8a80>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@sigvia/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
´´´

**Comment by balvig** [comment]
I'm just writing a test for namespaced models right now :)

**Comment by thiagocifani** [comment]
Thanks, with nested routes only. ;) My api is a single rails app with 3 models respond_to json

```ruby
  resources :occurrences do
    resources :photos
    resources :voice_records
  end
```

**Comment by balvig** [comment]
Okay! Seems like it _does_ work with namespaced models, although the naming of the keys certainly seem like they could be improved...could you

1. Update your gem to 1.6
2. Check out the commit in https://github.com/balvig/spyke/commit/00618beddff61d8374e0b8291ff6ceba8c638234 and try to emulate the settings there?
3. Maybe install a logger for Faraday (the one from https://github.com/yourkarma/faraday-conductivity is pretty good) so you can see if any http requests/response go out?

**Comment by thiagocifani** [comment]
My class is not inside a explicit namespace or module, it just use it cause I have a folder and the autoload do it automatically.

**Comment by thiagocifani** [comment]
Trying your approach.

**Comment by thiagocifani** [comment]
It is weird, my call is not firing any action. 

```
 Tro::Occurrence.all.first.photos.first
Started GET request to: http://localhost:3000/occurrences
Request Headers:
----------------
User-Agent : Faraday v0.9.1

Request Body:
-------------


Response from GET http://localhost:3000/occurrences; Status: 200; Time: 12.1ms
Response Headers:
----------------
x-frame-options        : SAMEORIGIN
x-xss-protection       : 1; mode=block
x-content-type-options : nosniff
content-type           : application/json; charset=utf-8
etag                   : "cf9a5d14082a8774d501839a908d48c8"
cache-control          : max-age=0, private, must-revalidate
x-request-id           : 1e5b7ad9-11c2-4ac1-b18e-fcb5fbb261eb
x-runtime              : 0.009739
connection             : close
server                 : thin

Response Body:
-------------
{"occurrences":[{"id":1,"title":"Título legal","description":"Descrição mais legal ainda.","x":-19.1513555390899,"y":-48.9631083745888,"token":"6ut5jcd5kbs4ffffffffaba9c71a","updated_at":"2015-01-16T16:29:50.788Z","created_at":"2015-01-16T16:29:50.788Z","urgency":3,"photos":[],"voice_record":null},{"id":2,"title":"Acidente com Ferrari","description":"Happens","x":-19.1513566666667,"y":-48.9631044444444,"token":"6ut5jcd5kbr5ffffffffaba9c71a","updated_at":"2015-01-16T16:29:54.347Z","created_at":"2015-01-16T16:29:54.347Z","urgency":5,"photos":[{"description":"Oh noes!","image":"http://s3.amazonaws.com/tro-devel/photos/images/1/original.jpg?1421425790","medium":"http://s3.amazonaws.com/tro-devel/photos/images/1/medium.jpg?1421425790","thumb":"http://s3.amazonaws.com/tro-devel/photos/images/1/thumb.jpg?1421425790"}],"voice_record":null}]}

  Spyke (13.0ms)  GET http://localhost:3000/occurrences [200]
=> nil

```

**Comment by thiagocifani** [comment]
without classname

```ruby

Tro::Occurrence.all.first.photos.first
Started GET request to: http://localhost:3000/occurrences
Request Headers:
----------------
User-Agent : Faraday v0.9.1

Request Body:
-------------


Response from GET http://localhost:3000/occurrences; Status: 200; Time: 12.8ms
Response Headers:
----------------
x-frame-options        : SAMEORIGIN
x-xss-protection       : 1; mode=block
x-content-type-options : nosniff
content-type           : application/json; charset=utf-8
etag                   : "cf9a5d14082a8774d501839a908d48c8"
cache-control          : max-age=0, private, must-revalidate
x-request-id           : 987c4c98-e805-4319-ac9b-b03ff2991dd4
x-runtime              : 0.010402
connection             : close
server                 : thin

Response Body:
-------------
{"occurrences":[{"id":1,"title":"Título legal","description":"Descrição mais legal ainda.","x":-19.1513555390899,"y":-48.9631083745888,"token":"6ut5jcd5kbs4ffffffffaba9c71a","updated_at":"2015-01-16T16:29:50.788Z","created_at":"2015-01-16T16:29:50.788Z","urgency":3,"photos":[],"voice_record":null},{"id":2,"title":"Acidente com Ferrari","description":"Happens","x":-19.1513566666667,"y":-48.9631044444444,"token":"6ut5jcd5kbr5ffffffffaba9c71a","updated_at":"2015-01-16T16:29:54.347Z","created_at":"2015-01-16T16:29:54.347Z","urgency":5,"photos":[{"description":"Oh noes!","image":"http://s3.amazonaws.com/tro-devel/photos/images/1/original.jpg?1421425790","medium":"http://s3.amazonaws.com/tro-devel/photos/images/1/medium.jpg?1421425790","thumb":"http://s3.amazonaws.com/tro-devel/photos/images/1/thumb.jpg?1421425790"}],"voice_record":null}]}

  Spyke (13.8ms)  GET http://localhost:3000/occurrences [200]
   (1.8ms)  SELECT f_geometry_column,coord_dimension,srid,type FROM geometry_columns WHERE f_table_name='photos'
NoMethodError: undefined method `new_collection_from_result' for #<Class:0x0000000a80dd60>
from /home/thiagocifani/.rvm/gems/ruby-2.1.2@sigvia/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing'


```

**Comment by thiagocifani** [comment]
The namespace is not in my api app, only in my server app where spyke is installed.

**Comment by thiagocifani** [comment]
Actually it is working now. class_name was the problem, without it it fails.

thanks for your attention. 

you are awesome. :+1:

**Comment by balvig** [comment]
Great to hear it! :blush:  Glad we could solve it, and thanks for giving me the opportunity to test out namespaces :+1:
