### ISSUE TITLE
Tests fail when using Ruby 2.5

### ISSUE THREAD

**Issue by paulvt** [balvig/spyke#99]
Some of the tests fail when running them on Ruby 2.5:

```
  test_custom_request_with_symbol_and_appended_scope              FAIL (0.16s)
Minitest::Assertion:         The request GET http://sushi.com/recipes/recent?status=published was expected to execute 1 time but it executed 0 times
        
        The following requests were made:
        
        GET http://sushi.com/recipes//recent?status=published with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Faraday v0.15.2'} was made 1 time
        
        ============================================================
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/assertion_failure.rb:7:in `failure'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/api.rb:86:in `assert_request_requested'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/minitest.rb:29:in `block (3 levels) in <top (required)>'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/api.rb:26:in `assert_requested'
        test/custom_request_test.rb:33:in `test_custom_request_with_symbol_and_appended_scope'

  test_create_on_custom_request                                   FAIL (0.35s)
Minitest::Assertion:         The request POST http://sushi.com/recipes/recent with body {"recipe"=>{"status"=>"published"}} was expected to execute 1 time but it executed 0 times
        
        The following requests were made:
        
        POST http://sushi.com/recipes//recent with body '{"recipe":{"status":"published"}}' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type'=>'application/json', 'User-Agent'=>'Faraday v0.15.2'} was made 1 time
        
        ============================================================
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/assertion_failure.rb:7:in `failure'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/api.rb:86:in `assert_request_requested'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/minitest.rb:29:in `block (3 levels) in <top (required)>'
        /home/player/sources/vendor/spyke/vendor/bundle/ruby/2.5.0/gems/webmock-3.4.2/lib/webmock/api.rb:26:in `assert_requested'
        test/custom_request_test.rb:39:in `test_create_on_custom_request'
```

The problem occurs because `#with` does something different for a symbol or a string argument. For a string argument, it just replaces the URL path, for a symbol, it appends it, leaving "/(id:)" in there which leads to a double slash in the final URL path, which in turn leads to different Faraday/Webmock (?) behaviour between Ruby 2.3 and 2.5.

Btw, what is the idea behind the difference in argument type handling?

I see that Travis only tests for Ruby 2.3.  You might want to expand that too?

**Comment by balvig** [comment]
Thanks for the heads up @paulvt! Fixed in #100 

> Btw, what is the idea behind the difference in argument type handling?

Basically a bit of convenience if you already have a base path set up and need access to different collections/filterings for example, ie:

```ruby
class Recipe < Spyke::Base
  uri "/recipes(/:id)"
end

Recipe.with(:recent) # => GET /recipes/recent
Recipe.with(:published) # => GET /recipes/published
Recipe.with(:featured) # => GET /recipes/featured

# Which would be the equivalent of

Recipe.with("recipes/recent")
Recipe.with("recipes/published")
Recipe.with("recipes/featured")
```
